version: '3'
services:
    server1:
        build: .
        environment:
        - npm_package_config_configPath=./docker/server1.env
        ports:
        - "4000:4000"
    server2:
        build: .
        environment:
            - npm_package_config_configPath=./docker/server2.env
        ports:
            - "5000:5000"